#!/usr/bin/env bash

set -Eeuo pipefail

# shellcheck disable=SC1091

# use variables from config file (unRAID specific)
if [[ -r /boot/config/plugins/ugreenleds-driver/settings.cfg ]]; then
	source "/boot/config/plugins/ugreenleds-driver/settings.cfg"
fi

# load environment variables
if [[ -r /etc/ugreen-leds.conf ]]; then
	source "/etc/ugreen-leds.conf"
fi

# led-disk mapping (see https://github.com/miskcoo/ugreen_dx4600_leds_controller/pull/4)
MAPPING_METHOD="${MAPPING_METHOD:=ata}" # ata, hctl, serial
atas=("ata1" "ata2" "ata3" "ata4" "ata5" "ata6" "ata7" "ata8" "ata9")

# hctl, $> lsblk -S -x hctl -o hctl,serial,name
# NOTE: It is reported that the order below should be adjusted for each model.
#       Please check the disk mapping section in https://github.com/miskcoo/ugreen_dx4600_leds_controller/blob/master/README.md.
hctl_map=("0:0:0:0" "1:0:0:0" "2:0:0:0" "3:0:0:0" "4:0:0:0" "5:0:0:0" "6:0:0:0" "7:0:0:0")

if which dmidecode > /dev/null; then
	product_name=$(dmidecode --string system-product-name)
	case "$product_name" in
		DXP6800*)   # tested on DXP6800 Pro
			echo "Found UGREEN DXP6800 series"
			hctl_map=("2:0:0:0" "3:0:0:0" "4:0:0:0" "5:0:0:0" "0:0:0:0" "1:0:0:0")
			atas=("ata3" "ata4" "ata5" "ata6" "ata1" "ata2")
			;;
		DX4600*)   # tested on DX4600 Pro
			echo "Found UGREEN DX4600 series"
			;;
		DX4700*)
			echo "Found UGREEN DX4700 series"
			;;
		DXP2800*)   # see issue #19
			echo "Found UGREEN DXP2800 series"
			;;
		DXP4800*)
			echo "Found UGREEN DXP4800 series"
			;;
		DXP8800*)  # tested on DXP8800 Plus
			echo "Found UGREEN DXP8800 series"
			# using the default mapping
			;;
		*)
			if [[ "$MAPPING_METHOD" == "hctl" || "$MAPPING_METHOD" == "ata" ]]; then
				echo -e "\033[0;31mUsing the default HCTL order. Please check it maps to your disk slots correctly."
				echo -e "If you confirm that the HCTL order is correct, or find it is different, you can "
				echo -e "submit an issue to let us know, so we can update the script."
				echo -e "Please read the disk mapping section in the link below for more details. "
				echo -e "   https://github.com/miskcoo/ugreen_dx4600_leds_controller/blob/master/README.md\033[0m"
			fi
			;;
	esac
elif [[ "$MAPPING_METHOD" == "hctl" || "$MAPPING_METHOD" == "ata" ]]; then
	echo -e "\033[0;31minstalling the tool $(dmidecode) is suggested; otherwise the script cannot detect your device and adjust the hctl/ata\033[0m"
fi >&2

if [[ "$MAPPING_METHOD" == "ata" ]]; then
	"${0}-ata"
elif [[ "$MAPPING_METHOD" == hctl || "$MAPPING_METHOD" == serial ]]; then
	lsblk -S -o name,"$MAPPING_METHOD",tran | grep sata
else
	echo Unsupported mapping method: "$MAPPING_METHOD"
	exit 1
fi
